version: "3"
services:
    senate-app:
        image: swayamjeet/senate_app:dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./src:/app/src
        env_file:
            - ./.env.dev